import type {
  User, Author, Book, Chapter, BookChunk, ReadingProgress,
  ChatConversation, ChatMessage, SocialConnection, BookWithAuthor
} from "@/types";

// ============================================================
// USERS
// ============================================================
export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Jeff Parker",
    email: "jeff@example.com",
    avatar_url: null,
    role: "author",
    bio: "History enthusiast and tech founder",
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "user-2",
    name: "Sarah Chen",
    email: "sarah@example.com",
    avatar_url: null,
    role: "reader",
    bio: "Avid reader, classics lover",
    created_at: "2025-06-20T10:00:00Z",
    updated_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "user-3",
    name: "Marcus Webb",
    email: "marcus@example.com",
    avatar_url: null,
    role: "reader",
    bio: "PhD candidate in Ancient History",
    created_at: "2025-09-10T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "user-4",
    name: "Dr. Elena Vasquez",
    email: "elena@example.com",
    avatar_url: null,
    role: "author",
    bio: "Professor of Neuroscience, bestselling author",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "user-5",
    name: "Alex Kim",
    email: "alex@example.com",
    avatar_url: null,
    role: "author",
    bio: "Tech entrepreneur, AI researcher",
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2026-03-02T10:00:00Z",
  },
];

// ============================================================
// AUTHORS
// ============================================================
export const mockAuthors: Author[] = [
  {
    id: "author-1",
    user_id: "user-1",
    display_name: "Edward Gibbon",
    bio: "Edward Gibbon (1737–1794) was an English historian, writer, and Member of Parliament. His most important work, The History of the Decline and Fall of the Roman Empire, was published in six volumes between 1776 and 1789 and is renowned for the quality and irony of its prose, its use of primary sources, and its incisive analysis of how a civilization at its peak can gradually decline.",
    avatar_url: "/images/gibbon-portrait.jpg",
    social_links: {
      x_handle: "gibbon_history",
      website: "https://example.com/gibbon",
    },
    total_books: 1,
    total_reads: 284500,
    verified: true,
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "author-2",
    user_id: "user-4",
    display_name: "Dr. Elena Vasquez",
    bio: "Professor of Neuroscience at Stanford University. Author of 'The Plastic Brain' and 'Mind Architects'. Her work focuses on neuroplasticity and the intersection of cognitive science with everyday decision-making and human behavior.",
    avatar_url: "/images/elena-avatar.jpg",
    social_links: {
      x_handle: "dr_vasquez_neuro",
      tiktok_handle: "brainscience101",
      website: "https://elenavasquez.com",
    },
    total_books: 2,
    total_reads: 156200,
    verified: true,
    created_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "author-3",
    user_id: "user-5",
    display_name: "Alex Kim",
    bio: "Former CTO of a YC-backed startup turned author. Writes about scaling technology companies, engineering culture, and the human side of building products. Based in San Francisco.",
    avatar_url: "/images/alex-avatar.jpg",
    social_links: {
      x_handle: "alexkimtech",
      website: "https://alexkim.dev",
    },
    total_books: 3,
    total_reads: 189400,
    verified: true,
    created_at: "2025-04-15T10:00:00Z",
  },
];

// ============================================================
// BOOKS
// ============================================================
export const mockBooks: Book[] = [
  {
    id: "book-1",
    author_id: "author-1",
    title: "The History of the Decline and Fall of the Roman Empire",
    description: "A monumental work of historical literature spanning thirteen centuries. Gibbon's masterpiece examines the gradual decline of Roman civilization from the height of the Antonine emperors through the fall of Constantinople in 1453. Through meticulous research and elegant prose, Gibbon traces how a civilization that conquered and ruled the known world eventually fragmented under internal pressures and external invasions.",
    cover_url: "/images/gibbon-cover.jpg",
    category: "History",
    tags: ["ancient rome", "history", "classics", "civilization", "public domain", "decline", "empire"],
    price: 0,
    currency: "USD",
    total_reads: 284500,
    total_chats: 45200,
    average_rating: 4.8,
    rating_count: 12840,
    featured: true,
    published_date: "1776-02-17T00:00:00Z",
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
    ai_config: {
      system_prompt: "You are an AI assistant helping readers explore Edward Gibbon's monumental 'The History of the Decline and Fall of the Roman Empire.' Provide scholarly yet accessible analysis. Always cite specific chapters and passages. Maintain Gibbon's characteristic wit and ironic tone when appropriate. Focus on historical accuracy while explaining how Gibbon's interpretations have influenced modern historiography.",
      temperature: 0.7,
      max_tokens: 2000,
    },
  },
  {
    id: "book-2",
    author_id: "author-2",
    title: "The Plastic Brain: How Neuroscience Reveals Our Capacity for Transformation",
    description: "An exploration of neuroplasticity and how our brains remain adaptable throughout our lives. Vasquez synthesizes decades of neuroscience research to show readers how understanding brain plasticity can unlock personal transformation and resilience.",
    cover_url: "/images/plastic-brain-cover.jpg",
    category: "Neuroscience",
    tags: ["neuroscience", "brain", "psychology", "plasticity", "self-improvement"],
    price: 14.99,
    currency: "USD",
    total_reads: 87650,
    total_chats: 12340,
    average_rating: 4.6,
    rating_count: 4520,
    featured: true,
    published_date: "2023-09-12T00:00:00Z",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2026-02-20T10:00:00Z",
    ai_config: {
      system_prompt: "You are an expert neuroscience assistant helping readers understand Dr. Vasquez's insights on neuroplasticity and brain transformation. Explain concepts clearly with real-world examples. Connect neuroscience principles to practical applications in daily life.",
      temperature: 0.7,
      max_tokens: 1500,
    },
  },
  {
    id: "book-3",
    author_id: "author-3",
    title: "Scale Fast, Stay Human: Engineering Culture for Growth",
    description: "From a former CTO who led scaling efforts at multiple startups. This book reveals how to build engineering teams and culture that remain strong and cohesive as companies grow from 10 to 1000+ engineers. Practical frameworks, real war stories, and actionable advice.",
    cover_url: "/images/scale-fast-cover.jpg",
    category: "Business",
    tags: ["startup", "engineering", "culture", "scaling", "leadership"],
    price: 12.99,
    currency: "USD",
    total_reads: 45230,
    total_chats: 8920,
    average_rating: 4.7,
    rating_count: 2840,
    featured: false,
    published_date: "2024-03-15T00:00:00Z",
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2026-02-28T10:00:00Z",
    ai_config: {
      system_prompt: "You are a business advisor helping readers apply Alex Kim's scaling frameworks to their own engineering organizations. Provide practical insights on team structure, culture, and growth strategies. Reference real examples from the book.",
      temperature: 0.75,
      max_tokens: 1500,
    },
  },
  {
    id: "book-4",
    author_id: "author-2",
    title: "Mind Architects: Building Intentional Mental Habits",
    description: "A practical guide to designing your mental architecture for success, happiness, and resilience. Vasquez combines cognitive psychology with neuroscience to explain how intentional habit formation can rewire your brain's default pathways.",
    cover_url: "/images/mind-architects-cover.jpg",
    category: "Psychology",
    tags: ["psychology", "habits", "cognitive science", "self-help", "neuroscience"],
    price: 16.99,
    currency: "USD",
    total_reads: 62450,
    total_chats: 9870,
    average_rating: 4.5,
    rating_count: 3210,
    featured: false,
    published_date: "2024-07-22T00:00:00Z",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2026-02-25T10:00:00Z",
    ai_config: {
      system_prompt: "You are a psychology coach helping readers design their mental habits using Vasquez's framework. Provide personalized insights, explain neuroscience concepts clearly, and help readers identify practical steps for their own growth.",
      temperature: 0.7,
      max_tokens: 1500,
    },
  },
  {
    id: "book-5",
    author_id: "author-3",
    title: "The Async Manifesto: Building Remote-First Teams",
    description: "A manifesto and practical guide for building effective remote and distributed teams. Kim explores asynchronous communication patterns, time zone management, and the future of work in a fully distributed world.",
    cover_url: "/images/async-manifesto-cover.jpg",
    category: "Technology",
    tags: ["remote work", "async", "distributed teams", "productivity", "future of work"],
    price: 9.99,
    currency: "USD",
    total_reads: 34120,
    total_chats: 5670,
    average_rating: 4.4,
    rating_count: 1850,
    featured: false,
    published_date: "2024-01-08T00:00:00Z",
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2026-02-18T10:00:00Z",
    ai_config: {
      system_prompt: "You are an expert on distributed team dynamics and async communication. Help readers implement Kim's principles in their organizations. Discuss challenges specific to remote teams and provide solutions based on the book.",
      temperature: 0.7,
      max_tokens: 1500,
    },
  },
  {
    id: "book-6",
    author_id: "author-3",
    title: "Stoic Engineers: Wisdom From Ancient Philosophy for Modern Problem Solving",
    description: "An exploration of Stoic philosophy applied to engineering and technology leadership. Kim shows how ancient wisdom on resilience, focus, and virtue can help modern engineers and technologists navigate uncertainty and build lasting impact.",
    cover_url: "/images/stoic-engineers-cover.jpg",
    category: "Philosophy",
    tags: ["stoicism", "philosophy", "engineering", "leadership", "wisdom"],
    price: 11.99,
    currency: "USD",
    total_reads: 28450,
    total_chats: 4320,
    average_rating: 4.6,
    rating_count: 1560,
    featured: false,
    published_date: "2024-11-01T00:00:00Z",
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2026-03-02T10:00:00Z",
    ai_config: {
      system_prompt: "You are a Stoic philosophy expert helping engineers and technologists apply ancient wisdom to modern challenges. Explain Stoic principles clearly, relate them to contemporary engineering problems, and help readers find practical applications.",
      temperature: 0.7,
      max_tokens: 1500,
    },
  },
];

// ============================================================
// CHAPTERS
// ============================================================
export const mockChapters: Chapter[] = [
  {
    id: "chapter-1",
    book_id: "book-1",
    chapter_number: 1,
    title: "The Extent and Military Force of the Roman Empire in the Age of the Antonines",
    description: "An examination of Rome's vast territorial extent and military organization under the peaceful emperors of the second century.",
    content: `The Roman Empire under the Antonine emperors represented the zenith of human civilization and the greatest territorial expanse ever achieved by a single political entity. At the height of its power under Antoninus Pius and Marcus Aurelius, Rome exercised dominion over three million square miles and governed upwards of seventy million subjects of various races and religions. The empire stretched from the Atlantic Ocean in the west to the Euphrates River in the east, from the Rhine and Danube rivers in the north to the deserts of Africa in the south. This vast territory was held together not primarily by military force, but by the remarkable administrative apparatus, the widespread use of Latin language and culture, and the prestige of Rome itself. The military forces of Rome during this period numbered approximately 450,000 men distributed across numerous legions and auxiliary troops stationed on the frontiers and within the provinces. The legions themselves represented the most advanced military organization of the ancient world, consisting of approximately 5,000 men each, subdivided into centuries and cohorts. Each legion was staffed with professional soldiers who had undergone rigorous training and who maintained strict discipline. The auxiliary troops, composed largely of barbarian warriors who had adopted Roman military organization and tactics, numbered approximately 200,000 men and served as both frontier guards and supplementary forces to the legions. The Roman navy, once the dominant force in the Mediterranean, had largely abandoned its role of aggressive expansion and instead served primarily to protect commerce and suppress piracy. The remarkable fact was that despite the vast extent of the empire and the number of its enemies, the empire during the Antonine period enjoyed what Gibbon would characterize as a golden age of peace and prosperity, with the military forces engaged primarily in holding and polishing existing possessions rather than in bold acts of conquest or expansion.`,
    word_count: 287,
    reading_time_minutes: 8,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "chapter-2",
    book_id: "book-1",
    chapter_number: 2,
    title: "Of the Union and Internal Prosperity of the Roman Empire in the Age of the Antonines",
    description: "Gibbon considers the internal peace, economic prosperity, and cultural unity that prevailed throughout the empire during the second century.",
    content: `The internal prosperity of the Roman Empire during the age of the Antonines was perhaps equally remarkable as its military organization and territorial extent. The absence of civil war for a period of nearly eighty years, from the accession of Nerva to the death of Commodus, allowed the accumulation of capital, the flourishing of commerce, and the development of a sophisticated cultural and intellectual life that extended far beyond the city of Rome itself. The provinces, having largely abandoned the parochial and narrow sentiments of earlier ages, came to regard themselves as integral parts of a greater whole and participated enthusiastically in Roman culture, religion, and governmental structures. Roads extended throughout the empire, facilitating commerce and communication. Cities modeled after Rome itself arose in distant lands, complete with forums, theaters, baths, and temples in the Roman style. The Latin language, while not universal, served as the lingua franca of educated classes and government officials across the empire. Economic activity flourished: Egyptian grain fed the city of Rome and other large urban centers; wine and oil from Italia, Gaul, and the provinces supplied extensive trade networks; and luxury goods flowed from the far reaches of the world through the Red Sea and overland routes. The accumulation of wealth among provincial elites paralleled that in Italy itself, and these provincial notables eagerly participated in the artistic and intellectual pursuits that characterized Roman civilization. The Antonine period saw the flourishing of Roman jurisprudence, the development of mature Stoic and Platonic philosophy, the heights of Roman oratory and literature, and remarkable achievements in engineering and architecture. Public works—aqueducts, theaters, roads, and public buildings—adorned cities throughout the empire. The Pax Romana had created circumstances in which prosperity could accumulate and culture could flourish without fear of the rapine and destruction that warfare brings.`,
    word_count: 305,
    reading_time_minutes: 9,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "chapter-3",
    book_id: "book-1",
    chapter_number: 3,
    title: "Of the Constitution of the Roman Empire in the Age of the Antonines",
    description: "An analysis of the governmental structure and constitutional arrangement of the Roman Empire during its most prosperous period.",
    content: `The constitutional arrangement of the Roman Empire under the Antonines represented a remarkable synthesis of republican forms and monarchical reality, a fiction that proved remarkably durable and which contributed significantly to the stability and prosperity of the age. In theory, power remained vested in the Senate and the people of Rome; in practice, the emperor wielded supreme authority, having consolidated in his person the offices of tribune, consul, and censor. Yet the persistence of republican terminology and institutions provided a psychological continuity with Rome's glorious republican past and allowed the governing classes to participate in the illusion of their traditional authority. The emperor himself, particularly under rulers such as Antoninus Pius and Marcus Aurelius, was bound by the rule of law and by traditional expectations regarding his conduct. The emperors of this period sought consensus with the Senate, governed through established constitutional mechanisms, and maintained the fiction that they ruled as first among equals rather than as absolute despots. This remarkable arrangement proved stable precisely because it depended on the wisdom and moderation of the individual emperor—so long as capable men of restrained ambitions occupied the throne, the system functioned smoothly. The Senate, though stripped of much practical power, retained its prestige and its role in the validation and execution of imperial policy. The magistrates of the empire—proconsuls, legates, and prefects—governed the provinces through established hierarchies and received their authority from the center. A sophisticated bureaucracy, staffed by both free men and talented slaves, conducted the vast business of imperial administration. The provinces, having been incorporated into the empire after periods of conquest and resistance, had largely been integrated into the imperial system and accepted the legitimacy of Roman rule. This acceptance was facilitated partly by the demonstrated benefits of the Pax Romana and partly by the remarkable adaptability of Roman civilization in incorporating local customs, deities, and traditions into the broader framework of imperial culture.`,
    word_count: 318,
    reading_time_minutes: 10,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "chapter-4",
    book_id: "book-1",
    chapter_number: 15,
    title: "The Progress of the Christian Religion, and the Establishment of the Catholic Church in the Roman Empire",
    description: "Gibbon's analysis of Christianity's spread through the empire and its eventual establishment as the dominant religion, examining both its spiritual appeal and institutional development.",
    content: `The spread of Christianity throughout the Roman Empire remains one of the most remarkable historical phenomena, and it is to Gibbon's great credit that he recognized its profound significance in explaining the transformation of the ancient world. From its humble origins as a sect within Judaism confined to the city of Jerusalem, Christianity gradually expanded to encompass the Mediterranean world and eventually came to dominate the spiritual life of the entire Roman Empire. Several factors contributed to this remarkable expansion. First, Christianity offered to all people—regardless of social status, wealth, nationality, or education—the promise of salvation and eternal life, presented in simple and comprehensible terms. This universal message had appeal that transcended the narrow confines of Roman religion, which remained closely bound to the state and to the privileges of the governing classes. Second, the organizational structure of the Christian church, with its hierarchy of bishops, priests, and deacons, its councils, and its increasingly standardized doctrines, provided an institutional framework that proved remarkably resilient and adaptive. Third, the active proselytizing of Christian missionaries, combined with the conversion of the most powerful man in the empire—Constantine himself—gave Christianity unprecedented advantages in spreading its message. The transformation from persecuted sect to established religion occurred gradually over three centuries. Initially, Christians were viewed with suspicion by Roman authorities, who saw in their unwillingness to participate in the pagan religious ceremonies that bound society together a threat to public order and imperial authority. Yet even persecution, Gibbon observes with characteristic irony, may have strengthened rather than weakened the faith by creating a cohort of martyrs whose devotion commanded respect. By the time of Constantine, the faith had become so widely diffused among the population that the emperor's conversion represented a recognition of changing realities rather than a bold innovation. The establishment of Christianity as the official religion by the end of the fourth century marked a transformation not merely of the empire's religious character but of its entire cultural and intellectual orientation.`,
    word_count: 342,
    reading_time_minutes: 11,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "chapter-5",
    book_id: "book-2",
    chapter_number: 1,
    title: "Introduction: The Birth of Neuroplasticity",
    description: "The foundational chapter introducing the concept of neuroplasticity and its revolutionary implications for how we understand the brain.",
    content: `For most of the twentieth century, neuroscientists believed that the adult brain was largely fixed and immutable, its neural connections locked into place by early development and destined to remain unchanged for life. This doctrine of neural fixedness was supported by powerful theoretical frameworks and seemed confirmed by experimental evidence. However, beginning in the 1960s and accelerating dramatically in the 1990s, researchers began to accumulate evidence of remarkable plasticity in the adult brain. The term neuroplasticity—the brain's ability to physically change in response to experience—has revolutionized our understanding of ourselves. When we learn a new skill, such as playing a musical instrument or mastering a new language, our brain doesn't simply acquire new information; it physically changes. New neural connections form, synapses strengthen or weaken, and entire regions of the cortex can be recruited for new purposes. This chapter explores the evidence for neuroplasticity and its profound implications. We examine how the brain maintains its capacity for change throughout life, how experience literally shapes brain structure, and how these discoveries have been validated through neuroimaging studies, behavioral experiments, and clinical applications. The implications are stunning: we are not prisoners of our genetic inheritance or our past experiences; we possess the remarkable capacity to reshape our brains and, in doing so, to transform ourselves.`,
    word_count: 238,
    reading_time_minutes: 7,
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "chapter-6",
    book_id: "book-2",
    chapter_number: 2,
    title: "The Mechanisms of Change: How Experience Rewires the Brain",
    description: "A deep dive into the cellular and molecular mechanisms by which experience physically alters brain structure and function.",
    content: `Understanding neuroplasticity requires examining the cellular machinery that enables the brain to change. At the foundation of all learning and memory lies the synapse—the connection between neurons where information flows from one nerve cell to another. Each time we repeat an experience or practice a skill, the synapses involved in that activity become stronger. This synaptic strengthening occurs through a process called long-term potentiation, in which repeated stimulation leads to lasting increases in synaptic transmission. Conversely, synapses that are not used undergo long-term depression, weakening over time. This phenomenon—"neurons that fire together wire together"—explains the mechanical basis for learning and habit formation. Beyond synaptic changes, experience can trigger the growth of new neurons in specific brain regions, including the hippocampus, which is crucial for memory formation. Environmental enrichment—exposure to novel stimuli, physical exercise, and social interaction—promotes neurogenesis and appears to enhance cognitive function. Neuroimaging studies reveal that when people practice a skill repeatedly, the brain regions devoted to that skill expand, recruiting more neural tissue for the task. Famously, studies of London taxi drivers who have memorized the city's complex street layout show enlarged hippocampi compared to controls. When musicians begin training young and practice intensively, the regions of their cortex devoted to finger control expand dramatically. These physical changes in the brain correlate directly with improvements in performance and are reversible—when practice ceases, the neural expansion regresses. Understanding these mechanisms gives us concrete understanding of how intention and effort can reshape our neural architecture.`,
    word_count: 267,
    reading_time_minutes: 8,
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "chapter-7",
    book_id: "book-3",
    chapter_number: 1,
    title: "The Early Days: Lessons from Scaling from 10 to 50 Engineers",
    description: "Foundational principles for maintaining culture and communication in the earliest growth stages of an engineering organization.",
    content: `Scaling from a startup of ten engineers to fifty engineers seems like a straightforward growth trajectory, yet this period contains crucial lessons that establish patterns for all subsequent growth. At ten engineers, everyone knows everyone; decisions are made in hallway conversations; the entire product roadmap can fit in someone's head. The transition to fifty engineers requires establishing basic processes, creating clear communication channels, and making the first critical investments in organizational structure. The biggest mistake I've seen teams make at this stage is attempting to implement the processes and structures of a 500-person company. Premature formalization kills the agility and rapid iteration that characterize successful startups. Instead, this phase requires establishing just enough structure to enable coordination without killing the entrepreneurial energy that defined the team. Communication mechanisms become critical. At ten people, a single daily standup can coordinate the entire team. At fifty, you need multiple standups organized by function, cross-functional synchronization meetings, and written documentation that begins to substitute for hallway conversations. Yet these mechanisms must remain lightweight. RFCs (Requests for Comments) should be short and asynchronous; meetings should have clear agendas and time limits; and decision-making should remain decentralized. Hiring becomes increasingly important and increasingly difficult. The team must be explicit about what behaviors and characteristics comprise culture fit—this is not about hiring clones but about ensuring that new members share core values and work styles. I recommend involving the entire team in hiring and making culture assessment a primary criterion rather than a secondary concern. The first conflicts between original team members and new joiners emerge at this scale. Managing these conflicts requires transparency, empathy, and a commitment to maintaining the best aspects of early-stage culture while adapting to new realities.`,
    word_count: 291,
    reading_time_minutes: 9,
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "chapter-8",
    book_id: "book-3",
    chapter_number: 2,
    title: "The Middle Transition: Managing from 50 to 200 Engineers",
    description: "Strategies for maintaining engineering excellence and team cohesion as organizational complexity dramatically increases.",
    content: `The growth from fifty to two hundred engineers represents a qualitative shift rather than merely a quantitative one. At fifty engineers, the team still feels unified and small; at two hundred, it begins to feel like a large organization. This transition requires fundamental changes in structure, communication, and leadership approach. The most critical change is the emergence of middle management. When there are only fifty engineers, the CTO or VP Engineering can directly manage most technical decisions. At two hundred engineers, this becomes impossible. Building a strong middle management layer—engineering managers and technical leads who can make good decisions without constant escalation to the top—becomes essential. Yet this layering can introduce dangerous patterns: middle managers protecting their turf, information flowing up and down the chain without horizontal communication, and the loss of the unifying sense of shared mission. To counteract these risks, invest heavily in middle manager development and explicitly design organizational structures that facilitate cross-functional collaboration. Introduce formal engineering practices that had seemed unnecessary before. You need code review standards, architectural review processes, deployment procedures, and on-call rotations that ensure reliability and prevent knowledge silos. Documentation becomes critical—the hallway conversation no longer works; you need written specifications, design documents, and operational runbooks. This is where many teams falter, either by over-documenting (creating process theater that slows everything down) or under-documenting (creating confusion and knowledge fragmentation). Strike a balance: document architectural decisions, design proposals, and operational procedures; keep meetings focused and asynchronous-first; and trust engineers to make good local decisions without constant approval. Perhaps most importantly, double down on your hiring and team composition. The quality of people you bring in at this stage has outsized impact on the subsequent culture and capabilities of the organization.`,
    word_count: 301,
    reading_time_minutes: 10,
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "chapter-9",
    book_id: "book-4",
    chapter_number: 1,
    title: "Your Brain's Default Mode: Understanding Automatic Thinking",
    description: "Exploration of how the brain defaults to habitual patterns and how understanding this can help us intentionally rewire our responses.",
    content: `Your brain is exquisitely efficient at creating routines. When you brush your teeth, drive to work, or respond to criticism, your brain largely operates on automatic pilot, executing learned patterns with minimal conscious attention. This automatic processing is a feature, not a bug—it frees up mental resources for novel challenges and allows us to move through the world without consciously directing every action. However, this same efficiency creates problems. Your brain's default responses to stress, setback, or social threat often reflect patterns established long ago, shaped by early experiences and repeated hundreds of times. If your brain learned early that criticism means you're inadequate, your default response might be shame and defensiveness. If your brain learned to value constant productivity to feel worthy, your default response to rest might be guilt. These automatic patterns operate largely outside our conscious awareness and are therefore difficult to change. The first step toward intentional mental architecture is understanding these defaults. The brain's "default mode network" (a network of regions active when we're not engaged in specific tasks) seems particularly important in generating automatic thoughts and patterns. When we're not actively focused on something, this network generates an inner narrative reflecting our habitual thoughts and concerns. For many people, this default narrative is critical, anxious, or focused on threat. Understanding this is the foundation for change. We cannot intentionally rewire what we don't recognize. By bringing awareness to our automatic patterns—through mindfulness, self-observation, and reflection—we create the possibility of choice. We begin to see the gap between stimulus and response, and in that gap lies our freedom to act differently.`,
    word_count: 270,
    reading_time_minutes: 8,
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "chapter-10",
    book_id: "book-4",
    chapter_number: 2,
    title: "Designing Your Habits: The Architecture of Intention",
    description: "Practical frameworks for deliberately designing habits that align with your values and long-term goals.",
    content: `Once we understand how our current mental architecture operates, we can intentionally design new patterns. Habit formation involves three components: the cue that triggers behavior, the routine that comprises the behavior itself, and the reward that reinforces the pattern. To change a habit, we must understand all three components. Consider someone who eats when stressed. The cue is stress or negative emotion; the routine is eating snacks; the reward might be the comfort of familiar flavors and the distraction from discomfort. To change this pattern, we can keep the cue (stress happens regardless) and the reward (we still need emotional regulation) but change the routine to something healthier—perhaps a short walk, deep breathing, or calling a friend. The most effective habit change strategies work with the brain's preference for established patterns rather than against it. Your brain wants routines; they're energetically efficient. Your job as the architect of your own mind is to establish new routines that lead to better outcomes. Stack new habits onto existing routines: do your meditation right after your morning coffee, when the routine is already activated. Make good habits obvious: put your exercise clothes on your bed the night before. Make bad habits invisible: if you're trying to reduce social media, delete the apps from your phone. Make good habits attractive: join an exercise class so the social element reinforces the routine. Make bad habits unattractive: if you eat too much candy, buy it in inconvenient small packages rather than bulk. These principles—making behaviors obvious, attractive, easy, and satisfying—leverage the brain's preference for efficient patterns while guiding those patterns toward your chosen values and long-term goals.`,
    word_count: 287,
    reading_time_minutes: 9,
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "chapter-11",
    book_id: "book-5",
    chapter_number: 1,
    title: "The Synchronous Trap: Why Meetings are the Enemy of Async Work",
    description: "Analysis of how synchronous communication and meetings undermine remote team effectiveness and asynchronous work culture.",
    content: `Most distributed organizations make a fundamental mistake: they try to replicate the synchronous communication patterns of co-located teams across time zones and continents. This creates "synchronous work trapped in a distributed shell"—video calls at awkward hours for someone, documentation created after meetings rather than before them, and the constant context-switching that kills deep work. The synchronous trap emerges because synchronous communication (real-time conversation and meetings) feels productive. You can see faces, read body language, make decisions quickly, and feel a sense of immediate progress. Yet for distributed teams, synchronous communication creates systemic inefficiencies. If your team spans five time zones, any meeting is scheduled at a bad time for someone. People either stay up late, wake up early, or are excluded from critical discussions. Worse, synchronous communication encourages a culture where attendance at meetings becomes a proxy for productivity and commitment. Engineers who attend many meetings look busy; those who focus heads-down on actual work may be perceived as disengaged. The result is a culture where the default is to sync up, which creates spiraling meeting load that crowds out deep work. Async-first cultures flip this dynamic. The default is to write things down—design documents, architecture proposals, status updates—and to give people time to read, think, and respond thoughtfully. Meetings still happen, but only when truly necessary: for brainstorming, for building relationships, for decisions that genuinely require real-time dialogue. The async-first approach requires discipline: you cannot schedule a meeting whenever you want feedback; you must write clearly and give people adequate time to respond. But the efficiency gains are substantial. Research on knowledge workers shows that deep focus sessions of 90+ minutes produce the highest quality work, and frequent context-switching dramatically reduces productivity. Async-first work patterns protect these focus sessions.`,
    word_count: 308,
    reading_time_minutes: 10,
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "chapter-12",
    book_id: "book-5",
    chapter_number: 2,
    title: "Building Trust Across Distance: The Async Communication Framework",
    description: "Practical frameworks for maintaining trust, transparency, and strong relationships in fully distributed teams.",
    content: `Trust in distributed teams depends on visibility and communication, yet paradoxically, synchronous communication—which feels like it should build trust through real-time connection—is less effective for trust-building than strategic asynchronous communication. The key is ensuring that important information is documented, visible, and accessible. I recommend implementing several core async communication practices. First, have a public-by-default mindset. Instead of private messages or emails, use shared channels and documents where information is visible to the whole team. This creates transparency that builds trust. People can see what's being decided and why, and can access information without having to ask. Second, implement structured asynchronous updates. Weekly status updates from each team, shared in a common format and location, give everyone visibility into what others are working on. Monthly all-hands meetings (recorded for async consumption) keep the whole organization connected to top-level strategy. Third, write with clarity and context. Async communication requires better writing than synchronous communication. You can't lean on tone of voice or body language; you must be explicit about your intent and assumptions. When proposing something substantial, provide context, reasoning, alternative approaches, and reasoning for your recommendation. This level of clarity actually builds more trust than a quick sync conversation because people understand your thinking, not just the conclusion. Fourth, establish working agreements around response times. If async communication is to work, people need to know what responsiveness to expect. A synchronous expectation of response within 30 minutes combined with claims of async culture is actually the worst of both worlds—it prevents deep focus while still requiring constant attention. Instead, be explicit: regular updates within 24 hours, decisions on proposals within 3 business days, emergency issues within 1 hour. Fourth, maintain some synchronous touchpoints strategically. Monthly coffee chats between folks who work together, occasional virtual team offsites, and structured social time all build relationships that support asynchronous work.`,
    word_count: 318,
    reading_time_minutes: 10,
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "chapter-13",
    book_id: "book-6",
    chapter_number: 1,
    title: "Amor Fati: The Stoic Embrace of Challenge and Difficulty",
    description: "How the Stoic principle of loving what happens can transform our relationship with the obstacles and challenges inherent in engineering.",
    content: `Marcus Aurelius, Roman emperor and Stoic philosopher, wrote in his meditations: "A blazing fire makes flame and brightness out of everything that is thrown into it." This insight captures the essence of Stoic resilience: not merely enduring difficulty, but transforming it into fuel for growth and achievement. In engineering, we face constant challenges—projects fail, code breaks in production, requirements change, colleagues disappoint us, and technical debt accumulates. The Stoic approach is not to pretend these challenges don't exist or to respond with resignation. Rather, it is to embrace them as opportunities for growth and learning. Epictetus, a slave-born Stoic philosopher, taught that we have no control over external events but complete control over our judgments and responses. When your production system fails at midnight, you cannot control that the failure happened. But you can control how you think about it: as a catastrophe that exposes your incompetence, or as a valuable opportunity to improve your systems and your team's capability. The Stoic term "amor fati"—love of fate—describes this reframing. It doesn't mean you enjoy suffering for its own sake, but rather that you recognize that obstacles contain within them exactly the material you need to develop the virtues of resilience, practical wisdom, and courage. The engineering leader who approaches difficult decisions, team conflicts, or technical challenges with amor fati becomes someone whose team trusts in uncertain situations. They don't panic or blame; they think clearly and act with purpose. This mindset, once developed, becomes contagious. Teams led by engineers who embrace challenge rather than avoiding it tend to be more innovative and more resilient in the face of setbacks.`,
    word_count: 280,
    reading_time_minutes: 9,
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "chapter-14",
    book_id: "book-6",
    chapter_number: 2,
    title: "The Four Virtues: Wisdom, Courage, Temperance, and Justice in Engineering Leadership",
    description: "An examination of the classical Stoic virtues and their application to modern engineering leadership challenges.",
    content: `The Stoics identified four cardinal virtues: wisdom, courage, temperance, and justice. These aren't abstract moral concepts but practical guides for decision-making. Wisdom (phronesis) is the faculty of practical judgment—the ability to see clearly what a situation requires and to act accordingly. In engineering, this manifests as the ability to distinguish between problems that matter and problems that don't, to see the long-term implications of architectural decisions, and to maintain perspective when dealing with technical crises. Courage (andreia) doesn't mean fearlessness; it means acting rightly even when afraid. It's the courage to propose an unpopular refactoring because you know it's right; to give critical feedback to a colleague because you care about their growth; to admit when you've made a mistake rather than defending it. Temperance (sophrosyne) is moderation and self-discipline. In engineering, it manifests as the discipline to avoid over-engineering solutions, to say no to features that don't align with core strategy, and to recognize your own limitations. It also means the discipline to exercise, sleep adequately, and maintain emotional equilibrium rather than burning out chasing impossible deadlines. Justice (dikaiosyne) is fairness and right relationship. It means treating your team members with respect, recognizing contributions, and distributing work fairly. It means considering the impact of your decisions on all stakeholders, not just your immediate goals. These virtues are not isolated but mutually reinforcing. Wisdom without courage is mere cowardice dressed in thoughtful language. Courage without temperance is recklessness. Justice without the other virtues is empty compliance. As you develop these virtues in yourself, you model them for your team. Engineers who work for leaders who embody wisdom, courage, temperance, and justice experience less stress, higher engagement, and greater satisfaction.`,
    word_count: 304,
    reading_time_minutes: 10,
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
];

// ============================================================
// BOOK CHUNKS (for vector embedding and semantic search)
// ============================================================
export const mockChunks: BookChunk[] = [
  {
    id: "chunk-1",
    chapter_id: "chapter-1",
    book_id: "book-1",
    content: "The Roman Empire under the Antonine emperors represented the zenith of human civilization and the greatest territorial expanse ever achieved by a single political entity.",
    embedding: new Array(1536).fill(0.1),
    metadata: {
      chunk_index: 0,
      page_number: 1,
    },
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "chunk-2",
    chapter_id: "chapter-1",
    book_id: "book-1",
    content: "The military forces of Rome during this period numbered approximately 450,000 men distributed across numerous legions and auxiliary troops stationed on the frontiers and within the provinces.",
    embedding: new Array(1536).fill(0.11),
    metadata: {
      chunk_index: 1,
      page_number: 1,
    },
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "chunk-3",
    chapter_id: "chapter-2",
    book_id: "book-1",
    content: "The internal prosperity of the Roman Empire during the age of the Antonines was perhaps equally remarkable as its military organization and territorial extent.",
    embedding: new Array(1536).fill(0.12),
    metadata: {
      chunk_index: 0,
      page_number: 2,
    },
    created_at: "2025-01-15T10:00:00Z",
  },
];

// ============================================================
// READING PROGRESS
// ============================================================
export const mockReadingProgress: ReadingProgress[] = [
  {
    id: "progress-1",
    user_id: "user-2",
    book_id: "book-1",
    current_chapter_id: "chapter-2",
    progress_percent: 15,
    last_read_at: "2026-03-03T22:30:00Z",
    created_at: "2026-02-15T10:00:00Z",
    updated_at: "2026-03-03T22:30:00Z",
  },
  {
    id: "progress-2",
    user_id: "user-3",
    book_id: "book-1",
    current_chapter_id: "chapter-4",
    progress_percent: 28,
    last_read_at: "2026-03-02T18:15:00Z",
    created_at: "2026-02-28T10:00:00Z",
    updated_at: "2026-03-02T18:15:00Z",
  },
  {
    id: "progress-3",
    user_id: "user-2",
    book_id: "book-2",
    current_chapter_id: "chapter-5",
    progress_percent: 32,
    last_read_at: "2026-03-01T14:45:00Z",
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-03-01T14:45:00Z",
  },
  {
    id: "progress-4",
    user_id: "user-3",
    book_id: "book-3",
    current_chapter_id: "chapter-8",
    progress_percent: 45,
    last_read_at: "2026-03-03T19:20:00Z",
    created_at: "2026-02-18T10:00:00Z",
    updated_at: "2026-03-03T19:20:00Z",
  },
];

// ============================================================
// CHAT CONVERSATIONS
// ============================================================
export const mockConversations: ChatConversation[] = [
  {
    id: "conv-1",
    user_id: "user-2",
    book_id: "book-1",
    title: "Understanding Rome's Military Structure",
    created_at: "2026-02-20T15:30:00Z",
    updated_at: "2026-03-03T22:30:00Z",
    message_count: 8,
  },
  {
    id: "conv-2",
    user_id: "user-3",
    book_id: "book-1",
    title: "The Role of Christianity in Rome's Decline",
    created_at: "2026-02-25T10:00:00Z",
    updated_at: "2026-03-02T18:15:00Z",
    message_count: 12,
  },
  {
    id: "conv-3",
    user_id: "user-2",
    book_id: "book-2",
    title: "Practical Application of Neuroplasticity",
    created_at: "2026-03-01T16:45:00Z",
    updated_at: "2026-03-01T17:20:00Z",
    message_count: 5,
  },
];

// ============================================================
// CHAT MESSAGES
// ============================================================
export const mockMessages: ChatMessage[] = [
  {
    id: "msg-1",
    conversation_id: "conv-1",
    role: "user",
    content: "How did Rome maintain control over such a vast military force spread across so many regions?",
    citations: [],
    created_at: "2026-02-20T15:30:00Z",
  },
  {
    id: "msg-2",
    conversation_id: "conv-1",
    role: "assistant",
    content: "According to Gibbon in Chapter I, Rome maintained control through a sophisticated hierarchical structure of approximately 450,000 soldiers organized into legions of about 5,000 men each. The legions were subdivided into centuries and cohorts with professional soldiers who had undergone rigorous training. Additionally, auxiliary troops composed of barbarian warriors who had adopted Roman military organization numbered around 200,000 men. This structure allowed centralized command while distributing forces strategically across the empire's frontiers and provinces.",
    citations: [
      {
        chapter_id: "chapter-1",
        passage: "The military forces of Rome during this period numbered approximately 450,000 men distributed across numerous legions and auxiliary troops",
        relevance: 0.95,
      },
    ],
    created_at: "2026-02-20T15:35:00Z",
  },
  {
    id: "msg-3",
    conversation_id: "conv-1",
    role: "user",
    content: "Did the legions ever have to deal with widespread rebellions?",
    citations: [],
    created_at: "2026-02-20T15:40:00Z",
  },
  {
    id: "msg-4",
    conversation_id: "conv-1",
    role: "assistant",
    content: "Gibbon notes in Chapter II that the Antonine period was remarkable for the absence of widespread internal conflict. The Pax Romana had created circumstances where the provinces largely accepted Roman rule and participated in Roman culture. Rather than facing major rebellions, Rome's military forces were primarily engaged in holding existing possessions and maintaining frontier security against external threats. The prosperity and cultural integration that characterized the age meant that provincial populations had accepted the legitimacy of Roman governance.",
    citations: [
      {
        chapter_id: "chapter-2",
        passage: "The absence of civil war for a period of nearly eighty years allowed the accumulation of capital and the flourishing of commerce",
        relevance: 0.92,
      },
    ],
    created_at: "2026-02-20T15:45:00Z",
  },
  {
    id: "msg-5",
    conversation_id: "conv-2",
    role: "user",
    content: "Was Christianity a major factor in Rome's eventual decline?",
    citations: [],
    created_at: "2026-02-25T10:00:00Z",
  },
  {
    id: "msg-6",
    conversation_id: "conv-2",
    role: "assistant",
    content: "This is one of Gibbon's most famous and controversial arguments. In Chapter XV on the progress of Christianity, Gibbon argues that while Christianity offered universal salvation and had remarkable institutional organization, it also represented a significant cultural transformation. The religion's emphasis on spiritual rather than civic virtues, and some scholars' interpretations of passages discouraging worldly ambition, may have contributed to a shift in values. However, Gibbon presents this with characteristic irony and nuance—he recognizes that Christianity's spread was also a sign of Rome's transformation rather than merely a cause. The empire's decline was multifactorial, involving military pressure from Germanic tribes, economic strain, and administrative challenges.",
    citations: [
      {
        chapter_id: "chapter-4",
        passage: "Christianity offered to all people the promise of salvation and eternal life, which had appeal that transcended the narrow confines of Roman religion",
        relevance: 0.88,
      },
    ],
    created_at: "2026-02-25T10:10:00Z",
  },
  {
    id: "msg-7",
    conversation_id: "conv-3",
    role: "user",
    content: "How can I apply neuroplasticity concepts to overcome anxiety about public speaking?",
    citations: [],
    created_at: "2026-03-01T16:45:00Z",
  },
  {
    id: "msg-8",
    conversation_id: "conv-3",
    role: "assistant",
    content: "Dr. Vasquez explains in The Plastic Brain that repeated practice literally changes the brain regions involved in any skill. For public speaking anxiety, you can leverage neuroplasticity through systematic exposure and practice. Start with lower-stakes speaking opportunities (small groups, friendly audiences) and gradually increase difficulty. Each time you speak, the neural circuits involved in speaking and managing anxiety get refined and strengthened. The brain's fear response to public speaking is learned and therefore can be unlearned. Combine exposure practice with mindfulness to observe your anxiety without judgment, which activates different neural networks than those involved in the fear response itself.",
    citations: [
      {
        chapter_id: "chapter-5",
        passage: "When we learn a new skill, our brain physically changes through new neural connections and synapses strengthening",
        relevance: 0.90,
      },
    ],
    created_at: "2026-03-01T17:00:00Z",
  },
];

// ============================================================
// SOCIAL CONNECTIONS
// ============================================================
export const mockSocialConnections: SocialConnection[] = [
  {
    id: "social-1",
    follower_id: "user-2",
    following_id: "user-3",
    created_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "social-2",
    follower_id: "user-3",
    following_id: "user-2",
    created_at: "2026-02-15T10:00:00Z",
  },
];

// ============================================================
// BOOKS WITH AUTHORS (Joined view)
// ============================================================
export const mockBooksWithAuthors: BookWithAuthor[] = mockBooks.map((book) => ({
  ...book,
  author: mockAuthors.find((a) => a.id === book.author_id)!,
}));
