-- Fight poster: 1960s-style Ali vs Frazier promotional image for video wait screen
-- Generated by Nano Banana 2 (gemini-3.1-flash-image-preview) via Vercel AI SDK

ALTER TABLE debate_sessions ADD COLUMN IF NOT EXISTS poster_url TEXT;
